project:
  type: website
  output-dir: docs

website:
  title: "YIGIT ASIK, Data Scientist"
  site-url: https://yigitasik.github.io
  description: "Anything related to statistics, analytics, and data science"
  navbar:
    right:
      - about.qmd
      - icon: substack
        href: https://thereadstep.substack.com/
      - icon: github
        href: https://github.com/YigitAsik
      - icon: linkedin
        href: https://www.linkedin.com/in/yigitasik/
      - icon: twitter
        href: https://bsky.app/profile/yigas.bsky.social
      - icon: youtube
        href: https://www.youtube.com/@yigasIRL
      - icon: rss
        href: index.xml
format:
  html:
    theme:
      light: Lux
    css: styles.css