project:
  type: website
  output-dir: docs

website:
  title: "YIGIT ASIK, Data Scientist"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/YigitAsik
      - icon: linkedin
        href: https://www.linkedin.com/in/yigitasik/
      - icon: twitter
        href: https://bsky.app/profile/yigas.bsky.social
      - icon: youtube
        href: https://www.youtube.com/@yigasIRL
format:
  html:
    theme:
      light: Lux
    css: styles.css