---
title: "Man on a Mission: March-April 2025"
author: "Yiğit Aşık"
date: "2025-04-27"
categories: [monthly]
---

Another month has passed. In these monthly posts, I won't dive deep into every little bit of stuff that I studied during the month (that would be impossible), what I'll try to convey the taste to increase your appetite.

I haven't been around for the last month and a half since there are more important things in life other than a blog. Due to the situations in Turkey, which you can read more [here](https://www.bbc.com/news/topics/c207p54mdq3t), it was extremely hard to focus on anything other than politics or law (there is also earthquake threat) which I spent most of my time with during last month.

Other than these, I personally try to focus on Statistics nowadays which I'll be giving more information below.

---

### Gelman's *Regression and Other Stories (ROS)*

Gelman's ROS is the book that I've read a lot lately and really liked it. The book goes through Statistics but mainly from Bayesian perspective and uses simulations to facilitate understanding. The book uses R's `stanarm` package but there is port of it in Python called `Bambi` which I already started exploring. It felt a bit counterintuitive at first but played around with it and now it makes more sense.

Generally, I have been focusing on simulations and methods related to Bayesian framework which made me dive into MCMCs a bit (just the general ones, such as Metropolis or Gibbs). Alongside that, I have developed interest in hierarchical modeling which I think about using for my basketball analytics projects.

### Explainable AI

I've finished Molnar's [*Interpretable ML*](https://christophm.github.io/interpretable-ml-book/) a couple of months ago but he updated the book, so I have that opened in one of my tabs and will go through it soon.

### Sports Analytics

I have two Shiny Apps now related to Euroleague analytics:
- https://hooplytics.shinyapps.io/EL_Player_Stats
- https://hooplytics.shinyapps.io/EL_Team_Stats

I wanted to include the defensive related stats but Turkey's agenda got in the way, so I'm thinking about getting it done during May. I'll also write a blog post (or maybe even a YT video) about how to navigate through the apps.

---

That's pretty much all for now, I read/watched/listened a lot of politics and law related content but hoping to dial it down a bit to create more time for data science related topics (if Turkey allows me to focus on those things)...