---
title: "Man on a Mission: January 2025"
author: "Yiğit Aşık"
date: "2025-01-31"
categories: [monthly]
---

As I [promised at the start of the year](https://yigitasik.github.io/posts/Man%20on%20a%20Mission%20-%20Starting%202025/), here's what I have studied this month.

---

### Statistics

This month I finished [*Think Bayes*](https://allendowney.github.io/ThinkBayes2/) way before than I anticipated, and played with [PyMC](https://www.pymc.io/welcome.html) a bit. I really enjoyed the whole book but wanted to dive a bit deep so moved on to John Kruschke's [*Doing Bayesian Data Analysis*](https://www.sciencedirect.com/book/9780124058880/doing-bayesian-data-analysis#book-info) and I'm glad I did it. The book starts with main ideas of Bayesian view, *"Bayesian inference is reallocation of credibility across possibilities"* where credibility stands for probability and possibilities stand for possible values that our parameters can take when we attempt to model. After this introduction, Kruschke talks about what probabilities are and provides intuitive description for the distinction between *probability mass* and *probability density*. If you have trouble understanding probability distributions, you may want to take a look at it.

Bayesian stuff aside, I really enjoyed the interpretation of mean as minimized variance alongside how we end up with median and mode when we change the distance measure (e.g., l2 norm to l1 etc.). Also, I coded Metropolis Algorithm (1-D) by using the example in the MCMC chapter. You can find it on my GitHub under *learn-stats-with-sims*.

I'm currently at chapter 9, going through hierarchical models. We'll see if the book keeps me engaged throughout the upcoming chapters as well.

---

### Deep Learning (DL)

Well, I haven't done much for the DL. Throughout the year, amount of time I spent on statistics will gradually decline to open up space for DL. I've just started to [*Hands-On Machine Learning with Scikit-Learn, Keras, and TensorFlow*](https://www.oreilly.com/library/view/hands-on-machine-learning/9781492032632/), skimming through Scikit-Learn part to start with Keras and Tensorflow while not missing out on anything (despite using sklearn pretty often, I don't want to miss a useful thing that may come in handy in the future).

---

In terms of sports analytics or production level data science, I haven't done more than reading a few blog posts. Data science stuff aside, I have improved a lot on the website, added new functionalities such as widget to subscribe to the email list which allows you to get notified when I write a new post. It took quite some time to handle the front-end, so I count that as a win as well.

See you next month!